[project]
name = "loi-baserow-dump"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "acdh-baserow-pyutils>=0.11.0",
    "acdh-tei-pyutils>=1.6",
]
